const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),id=params.get('id'),video=$('#video'),returnLibraryFilter=['all','image','video'].includes(params.get('fromFilter'))?params.get('fromFilter'):'all';
let record,url,duration=0,cancelled=false;
init();
async function init(){await OpenScreenI18n.ready;record=await OpenScreenDB.get(id);if(!record?.blob){document.body.innerHTML=`<p>${OpenScreenI18n.t('Không tìm thấy video.')}</p>`;return}$('#name').value=record.name;url=URL.createObjectURL(record.blob);video.src=url;await new Promise(r=>video.addEventListener('loadedmetadata',r,{once:true}));duration=video.duration||record.duration/1000;['start','end'].forEach(x=>$(`#${x}`).max=duration);$('#start').value=0;$('#end').value=duration;$('#startTime').value=0;$('#endTime').value=duration.toFixed(1);updateLabels()}
function fmt(s){return OpenScreen.formatDuration(s*1000)}function updateLabels(){$('#startLabel').textContent=fmt(Number($('#start').value));$('#endLabel').textContent=fmt(Number($('#end').value))}
$('#start').addEventListener('input',()=>{if(Number($('#start').value)>=Number($('#end').value)-.1)$('#start').value=Math.max(0,Number($('#end').value)-.1);$('#startTime').value=Number($('#start').value).toFixed(1);video.currentTime=Number($('#start').value);updateLabels()});
$('#end').addEventListener('input',()=>{if(Number($('#end').value)<=Number($('#start').value)+.1)$('#end').value=Math.min(duration,Number($('#start').value)+.1);$('#endTime').value=Number($('#end').value).toFixed(1);video.currentTime=Number($('#end').value);updateLabels()});
$('#startTime').addEventListener('change',()=>{$('#start').value=Math.max(0,Math.min(Number($('#startTime').value),Number($('#end').value)-.1));$('#start').dispatchEvent(new Event('input'))});
$('#endTime').addEventListener('change',()=>{$('#end').value=Math.min(duration,Math.max(Number($('#endTime').value),Number($('#start').value)+.1));$('#end').dispatchEvent(new Event('input'))});
function updateOverlay(){const el=$('#textOverlay');el.textContent=$('#overlayText').value;el.className=$('#textPosition').value;el.style.color=$('#textColor').value;$('#shapeOverlay').style.display=$('#showBox').checked?'block':'none';$('#shapeOverlay').style.borderColor=$('#boxColor').value}
['overlayText','textPosition','textColor','showBox','boxColor'].forEach(x=>$(`#${x}`).addEventListener('input',updateOverlay));
$('#library').addEventListener('click',()=>location.href=chrome.runtime.getURL(`library/library.html?filter=${encodeURIComponent(returnLibraryFilter)}`));$('#export').addEventListener('click',exportVideo);$('#cancel').addEventListener('click',()=>cancelled=true);
async function seek(time){return new Promise(resolve=>{const done=()=>resolve();video.addEventListener('seeked',done,{once:true});video.currentTime=time})}
async function exportVideo(){
  const start=Number($('#start').value),end=Number($('#end').value);if(end-start<.1)return OpenScreen.toast(OpenScreenI18n.t('Đoạn chọn quá ngắn.'));cancelled=false;$('#processing').classList.remove('hidden');await seek(start);
  const out=document.createElement('canvas');out.width=video.videoWidth;out.height=video.videoHeight;const outCtx=out.getContext('2d'),stream=out.captureStream(30),sourceStream=video.captureStream?.();sourceStream?.getAudioTracks().forEach(track=>stream.addTrack(track));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(type=>MediaRecorder.isTypeSupported(type))||'';const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Math.max(8_000_000,(record.width||out.width)*5000)}),parts=[];recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};
  const done=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=e=>reject(e.error)});recorder.start(1000);video.muted=true;await video.play();
  await new Promise(resolve=>{const draw=()=>{outCtx.drawImage(video,0,0,out.width,out.height);drawOverlay(outCtx,out.width,out.height);const p=Math.min(1,(video.currentTime-start)/(end-start));$('#progressText').textContent=`${Math.round(p*100)}%`;if(cancelled||video.currentTime>=end||video.ended){video.pause();recorder.stop();resolve()}else requestAnimationFrame(draw)};draw()});await done;
  if(cancelled){$('#processing').classList.add('hidden');return}const blob=new Blob(parts,{type:mime}),newId=OpenScreen.uid('recording'),name=($('#name').value.trim()||record.name)+OpenScreenI18n.t(' — edited');await OpenScreenDB.save({id:newId,kind:'video',name,createdAt:Date.now(),duration:(end-start)*1000,width:out.width,height:out.height,mimeType:mime,extension:'webm',blob});$('#processing').classList.add('hidden');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${name.replace(/[\\/:*?"<>|]/g,'-')}.webm`;a.click();OpenScreen.toast(OpenScreenI18n.t('Đã xuất và lưu vào thư viện'))
}
function drawOverlay(c,w,h){const text=$('#overlayText').value;if(text){c.save();const size=Math.max(28,h*.055);c.font=`800 ${size}px Inter, sans-serif`;c.textAlign='center';c.textBaseline='middle';const pos=$('#textPosition').value,y=pos==='top'?h*.1:pos==='bottom'?h*.9:h*.5;c.lineWidth=Math.max(4,size*.13);c.strokeStyle='rgba(0,0,0,.65)';c.strokeText(text,w/2,y);c.fillStyle=$('#textColor').value;c.fillText(text,w/2,y);c.restore()}if($('#showBox').checked){c.save();c.strokeStyle=$('#boxColor').value;c.lineWidth=Math.max(5,h*.009);c.strokeRect(w*.22,h*.25,w*.56,h*.5);c.restore()}}
window.addEventListener('unload',()=>URL.revokeObjectURL(url));
